---
title: "Project - California Quail in BC"
author: "Tyler Stevenson, Foster Lockerbie, Seamus Riordan-Short"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%OS')`"
output:
  #pdf_document: default
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
```


* * *
## Loading Required Packages

```{r, message = FALSE}
#load packages
library(spatstat)
library(sf)
library(rgbif)
```

## Import Data

```{r}
#occ_download_wait('0002650-250402121839773')
data <- occ_download_get('0002650-250402121839773') %>%
  occ_download_import()
```


```{r}
# Filter for only British Columbia records
bc_quail <- data[data$stateProvince %in% 
                             c("British Columbia", 
                               "British Columbia (BC)", 
                               "British Columbia (Prov.)",
                               "Bc"), ]

```

```{r}
load("BC_Covariates.Rda")

#Identify Class of Each Element
sapply(DATA, class)

# Convert quail data to sf object
quail_df <- st_as_sf(bc_quail, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326, remove = FALSE)

# Remove duplicated coordinates
quail_df <- quail_df[!duplicated(st_coordinates(quail_df)), ]

# Convert window to sf
window_sf <- st_as_sf(DATA$Window)

# Ensure both quail coordinates and the window are in the same CRS
quail_df <- st_transform(quail_df, crs = st_crs(window_sf))

#Remove Points Outside the Window
inside_window <- st_intersects(quail_df, window_sf)
quail_df <- quail_df[sapply(inside_window, length) > 0, ]

# Extract the x and y coordinates of the quail
quail_coords <- st_coordinates(quail_df)

# Create the ppp object
quail_ppp <- ppp(x = quail_coords[, 1], y = quail_coords[, 2], window = as.owin(window_sf))


plot(quail_ppp)
```

```{r}
#Extract elevation information
elev <- DATA$Elevation

#Estimate Rho
rho <- rhohat(quail_ppp, elev)

plot(rho)
```


